name: Archive full list

on:
  check_run:
    types: [completed]

jobs:
  archive:
    name: Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Save to wayback machine
        uses: JamieMagee/wayback@v2
        with:
          url: https://yellow-blue-map.pages.dev/shops/
          saveErrors: false
          saveOutlinks: false
          saveScreenshot: false
